# Data cleaning
This notebook clean and process the raw data to prepare them for analysis

## Import libraries

In [1]:
import pandas as pd

## Load raw data

In [ ]:
df = pd.read_csv("..//1_datasets/HR-Employee-Attrition-raw.csv")
print(df.shape)
#df.info()
#df.describe()
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,1,...,1.0,80,0,8,0,1.0,6,4,0,5
1,49,No,Travel_Frequently,279.0,Research & Development,8,1.0,Life Sciences,1,2,...,4.0,80,1,10,3,3.0,10,7,1,7
2,37,Yes,Travel_Rarely,1373.0,Research & Development,2,2.0,Other,1,4,...,2.0,80,0,7,3,3.0,0,0,0,0
3,33,No,Travel_Frequently,1392.0,Research & Development,3,4.0,Life Sciences,1,5,...,3.0,80,0,8,3,3.0,8,7,3,0
4,27,No,Travel_Rarely,591.0,Research & Development,2,1.0,Medical,1,7,...,4.0,80,1,6,3,3.0,2,2,2,2

## Data cleaning

Check if there are any fields that contain NaN/null values

In [30]:
print(df.isnull().sum())

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   5
Department                  0
DistanceFromHome            0
Education                   3
EducationField              3
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     3
Gender                      0
HourlyRate                  0
JobInvolvement              2
JobLevel                    0
JobRole                     0
JobSatisfaction             3
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           2
RelationshipSatisfaction    3
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             3
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

Not all of the fields contain completed entries. It means, that some information is missed. The possible reasons of missed information are:
1. new employees have not submited surveys,
2. managers have not provided feedback for new employees
3. discrepancies in the data of the information system

Select only lines with NaN values and analyse them

In [39]:
nan_rows = df[df.isnull().any(axis=1)]
print(nan_rows.shape)
print(nan_rows.info())
nan_rows.head()

(13, 35)
<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 1470 to 1482
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       13 non-null     int64
 1   Attrition                 13 non-null     object
 2   BusinessTravel            13 non-null     object
 3   DailyRate                 8 non-null      float64
 4   Department                13 non-null     object
 5   DistanceFromHome          13 non-null     int64
 6   Education                 10 non-null     float64
 7   EducationField            10 non-null     object
 8   EmployeeCount             13 non-null     int64
 9   EmployeeNumber            13 non-null     int64
 10  EnvironmentSatisfaction   10 non-null     float64
 11  Gender                    13 non-null     object
 12  HourlyRate                13 non-null     int64
 13  JobInvolvement            11 non-null     float64
 14  JobLevel                  13 non-null     int64
 15  JobRole                   13 non-null     object
 16  JobSatisfaction           10 non-null     float64
 17  MaritalStatus             13 non-null     object
 18  MonthlyIncome             13 non-null     int64
 19  MonthlyRate               13 non-null     int64
 20  NumCompaniesWorked        13 non-null     int64
 21  Over18                    13 non-null     object
 22  OverTime                  13 non-null     object
 23  PercentSalaryHike         13 non-null     int64
 24  PerformanceRating         11 non-null     float64
 25  RelationshipSatisfaction  10 non-null     float64
 26  StandardHours             13 non-null     int64
 27  StockOptionLevel          13 non-null     int64
 28  TotalWorkingYears         13 non-null     int64
 29  TrainingTimesLastYear     13 non-null     int64
 30  WorkLifeBalance           10 non-null     float64
 31  YearsAtCompany            13 non-null     int64
 32  YearsInCurrentRole        13 non-null     int64
 33  YearsSinceLastPromotion   13 non-null     int64
 34  YearsWithCurrManager      13 non-null     int64
dtypes: float64(8), int64(18), object(9)
memory usage: 3.7+ KB
None

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1470,27,No,Travel_Rarely,NaN,Research & Development,2,1.0,Medical,1,2029,...,4.0,80,1,6,3,3.0,2,2,2,2
1471,24,Yes,Travel_Rarely,813.0,Research & Development,1,NaN,NaN,1,2030,...,1.0,80,1,6,2,2.0,2,0,2,0
1472,23,No,Travel_Rarely,541.0,Sales,2,1.0,Technical Degree,1,2033,...,3.0,80,1,3,3,3.0,0,0,0,0
1473,24,No,Travel_Rarely,NaN,Sales,3,2.0,Other,1,2039,...,1.0,80,1,4,2,2.0,3,2,0,2
1474,22,No,Travel_Rarely,534.0,Research & Development,15,3.0,Medical,1,2042,...,3.0,80,0,1,5,3.0,0,0,0,0

1. New employees have not submited surveys.
Periodically employees complete surveys ragarding their satisfaction or engagement in the work. There could be some new employees, who have not provided this information. The source of the employee's survey have the following filds: EnvironmentSatisfaction, JobSatisfaction, RelationshipSatisfaction, WorkLifeBalance.
Check if there are new employees who have not provided their surveys yet.

In [40]:
missed_survey_nan = df[df['JobSatisfaction'].isnull()]
print(missed_survey_nan.shape)
print(missed_survey_nan.info())
missed_survey_nan.head()

(3, 35)
<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1478 to 1482
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       3 non-null      int64
 1   Attrition                 3 non-null      object
 2   BusinessTravel            3 non-null      object
 3   DailyRate                 3 non-null      float64
 4   Department                3 non-null      object
 5   DistanceFromHome          3 non-null      int64
 6   Education                 3 non-null      float64
 7   EducationField            3 non-null      object
 8   EmployeeCount             3 non-null      int64
 9   EmployeeNumber            3 non-null      int64
 10  EnvironmentSatisfaction   0 non-null      float64
 11  Gender                    3 non-null      object
 12  HourlyRate                3 non-null      int64
 13  JobInvolvement            3 non-null      float64
 14  JobLevel                  3 non-null      int64
 15  JobRole                   3 non-null      object
 16  JobSatisfaction           0 non-null      float64
 17  MaritalStatus             3 non-null      object
 18  MonthlyIncome             3 non-null      int64
 19  MonthlyRate               3 non-null      int64
 20  NumCompaniesWorked        3 non-null      int64
 21  Over18                    3 non-null      object
 22  OverTime                  3 non-null      object
 23  PercentSalaryHike         3 non-null      int64
 24  PerformanceRating         3 non-null      float64
 25  RelationshipSatisfaction  0 non-null      float64
 26  StandardHours             3 non-null      int64
 27  StockOptionLevel          3 non-null      int64
 28  TotalWorkingYears         3 non-null      int64
 29  TrainingTimesLastYear     3 non-null      int64
 30  WorkLifeBalance           0 non-null      float64
 31  YearsAtCompany            3 non-null      int64
 32  YearsInCurrentRole        3 non-null      int64
 33  YearsSinceLastPromotion   3 non-null      int64
 34  YearsWithCurrManager      3 non-null      int64
dtypes: float64(8), int64(18), object(9)
memory usage: 864.0+ bytes
None

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1478,18,No,Travel_Rarely,812.0,Sales,10,3.0,Medical,1,2058,...,NaN,80,0,0,2,NaN,0,0,0,0
1481,27,No,Non-Travel,443.0,Research & Development,3,3.0,Medical,1,2066,...,NaN,80,3,0,6,NaN,0,0,0,0
1482,18,No,Non-Travel,287.0,Research & Development,5,2.0,Life Sciences,1,2067,...,NaN,80,0,0,2,NaN,0,0,0,0

There are 3 employees who worked in the company 0 years (field"YearsAtCompany") and have missed ('NaN') values for the fields: 'EnvironmentSatisfaction', 'JobSatisfaction', 'RelationshipSatisfaction', 'WorkLifeBalance'. These fields are poplated from the periodical surveys. Since the employees are new, they have not completed these surveys yet.

2. Managers have not provided feedback for new employees.
Periodically managers provide assessment of their suboridnates. In the case of new employees this assessment can be missed. The fileds: 'JobInvolvement', 'PerformanceRating' come from periodical manageres assesments.
Check if there are new employees who have not obtained manager's assesment yet.

In [41]:
missed_manager_assesment_nan = df[df['JobInvolvement'].isnull()]
print(missed_manager_assesment_nan.shape)
print(missed_manager_assesment_nan.info())
missed_manager_assesment_nan.head()

(2, 35)
<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, 1472 to 1474
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       2 non-null      int64
 1   Attrition                 2 non-null      object
 2   BusinessTravel            2 non-null      object
 3   DailyRate                 2 non-null      float64
 4   Department                2 non-null      object
 5   DistanceFromHome          2 non-null      int64
 6   Education                 2 non-null      float64
 7   EducationField            2 non-null      object
 8   EmployeeCount             2 non-null      int64
 9   EmployeeNumber            2 non-null      int64
 10  EnvironmentSatisfaction   2 non-null      float64
 11  Gender                    2 non-null      object
 12  HourlyRate                2 non-null      int64
 13  JobInvolvement            0 non-null      float64
 14  JobLevel                  2 non-null      int64
 15  JobRole                   2 non-null      object
 16  JobSatisfaction           2 non-null      float64
 17  MaritalStatus             2 non-null      object
 18  MonthlyIncome             2 non-null      int64
 19  MonthlyRate               2 non-null      int64
 20  NumCompaniesWorked        2 non-null      int64
 21  Over18                    2 non-null      object
 22  OverTime                  2 non-null      object
 23  PercentSalaryHike         2 non-null      int64
 24  PerformanceRating         0 non-null      float64
 25  RelationshipSatisfaction  2 non-null      float64
 26  StandardHours             2 non-null      int64
 27  StockOptionLevel          2 non-null      int64
 28  TotalWorkingYears         2 non-null      int64
 29  TrainingTimesLastYear     2 non-null      int64
 30  WorkLifeBalance           2 non-null      float64
 31  YearsAtCompany            2 non-null      int64
 32  YearsInCurrentRole        2 non-null      int64
 33  YearsSinceLastPromotion   2 non-null      int64
 34  YearsWithCurrManager      2 non-null      int64
dtypes: float64(8), int64(18), object(9)
memory usage: 576.0+ bytes
None

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1472,23,No,Travel_Rarely,541.0,Sales,2,1.0,Technical Degree,1,2033,...,3.0,80,1,3,3,3.0,0,0,0,0
1474,22,No,Travel_Rarely,534.0,Research & Development,15,3.0,Medical,1,2042,...,3.0,80,0,1,5,3.0,0,0,0,0

There are 2 employees who worked in the company 0 years (field"YearsAtCompany") and have missed ('NaN') values for the fields: 'JobInvolvement', 'PerformanceRating'. These fields are poplated from the periodical managers asesments. Since the employees are new, they have not abtained any manager's assessmant yet.

3. Discrepancies in the data of the information system
Not all the case (lines) that include blank values were explained by hipothesis 1 and 2. It means that there are other discrepancies in the data that have other reason of missed information (different from not completed surveys and missed manager's appraisal).

In [43]:
selected_indices = missed_survey_nan.index.union(missed_manager_assesment_nan.index)
rest_discrep_nan = nan_rows[~nan_rows.index.isin(selected_indices)]
print(rest_discrep_nan.shape)
print(rest_discrep_nan.info())
rest_discrep_nan.head()

(8, 35)
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 1470 to 1480
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       8 non-null      int64
 1   Attrition                 8 non-null      object
 2   BusinessTravel            8 non-null      object
 3   DailyRate                 3 non-null      float64
 4   Department                8 non-null      object
 5   DistanceFromHome          8 non-null      int64
 6   Education                 5 non-null      float64
 7   EducationField            5 non-null      object
 8   EmployeeCount             8 non-null      int64
 9   EmployeeNumber            8 non-null      int64
 10  EnvironmentSatisfaction   8 non-null      float64
 11  Gender                    8 non-null      object
 12  HourlyRate                8 non-null      int64
 13  JobInvolvement            8 non-null      float64
 14  JobLevel                  8 non-null      int64
 15  JobRole                   8 non-null      object
 16  JobSatisfaction           8 non-null      float64
 17  MaritalStatus             8 non-null      object
 18  MonthlyIncome             8 non-null      int64
 19  MonthlyRate               8 non-null      int64
 20  NumCompaniesWorked        8 non-null      int64
 21  Over18                    8 non-null      object
 22  OverTime                  8 non-null      object
 23  PercentSalaryHike         8 non-null      int64
 24  PerformanceRating         8 non-null      float64
 25  RelationshipSatisfaction  8 non-null      float64
 26  StandardHours             8 non-null      int64
 27  StockOptionLevel          8 non-null      int64
 28  TotalWorkingYears         8 non-null      int64
 29  TrainingTimesLastYear     8 non-null      int64
 30  WorkLifeBalance           8 non-null      float64
 31  YearsAtCompany            8 non-null      int64
 32  YearsInCurrentRole        8 non-null      int64
 33  YearsSinceLastPromotion   8 non-null      int64
 34  YearsWithCurrManager      8 non-null      int64
dtypes: float64(8), int64(18), object(9)
memory usage: 2.2+ KB
None

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1470,27,No,Travel_Rarely,NaN,Research & Development,2,1.0,Medical,1,2029,...,4.0,80,1,6,3,3.0,2,2,2,2
1471,24,Yes,Travel_Rarely,813.0,Research & Development,1,NaN,NaN,1,2030,...,1.0,80,1,6,2,2.0,2,0,2,0
1473,24,No,Travel_Rarely,NaN,Sales,3,2.0,Other,1,2039,...,1.0,80,1,4,2,2.0,3,2,0,2
1475,22,No,Travel_Rarely,NaN,Research & Development,19,1.0,Medical,1,2043,...,1.0,80,2,2,6,3.0,2,2,2,2
1476,42,No,Non-Travel,926.0,Research & Development,21,NaN,NaN,1,2047,...,2.0,80,1,11,5,3.0,5,3,0,2

There is no logical explanation for this missing information. The reason could be a lack of information during data migration from previous systems, or missing input from the responsible HR specialist. For the purpose of data abalysis all these cases should be expluded from the raw dataset. Existance of cases with blank values may produce distorted results?, especcialy for the tasks of correlation analysis.

Remove all the lines that include 'NaN' values.

In [44]:
df_cleaned = df.dropna()
print(df_cleaned.shape)
print(df_cleaned.info())
df_cleaned.head()

(1470, 35)
<class 'pandas.core.frame.DataFrame'>
Index: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   float64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   float64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   float64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   float64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   float64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   float64
 25  RelationshipSatisfaction  1470 non-null   float64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   float64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(8), int64(18), object(9)
memory usage: 413.4+ KB
None

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,1,...,1.0,80,0,8,0,1.0,6,4,0,5
1,49,No,Travel_Frequently,279.0,Research & Development,8,1.0,Life Sciences,1,2,...,4.0,80,1,10,3,3.0,10,7,1,7
2,37,Yes,Travel_Rarely,1373.0,Research & Development,2,2.0,Other,1,4,...,2.0,80,0,7,3,3.0,0,0,0,0
3,33,No,Travel_Frequently,1392.0,Research & Development,3,4.0,Life Sciences,1,5,...,3.0,80,0,8,3,3.0,8,7,3,0
4,27,No,Travel_Rarely,591.0,Research & Development,2,1.0,Medical,1,7,...,4.0,80,1,6,3,3.0,2,2,2,2

Save cleaned dataset in HR-Employee-Attrition.csv file

In [45]:
df_cleaned.to_csv('..//2_data_preparation/HR-Employee-Attrition.csv', index=False)

Review the created cleaned dataset to verify, that all the parameters of the data suit to data exploration and analysis tasks.

In [47]:
df_cl = pd.read_csv("..//2_data_preparation/HR-Employee-Attrition.csv")
print(df_cl.shape)
print(df_cl.info())
df_cl.head()

(1470, 35)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   float64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   float64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   float64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   float64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   float64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   float64
 25  RelationshipSatisfaction  1470 non-null   float64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   float64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(8), int64(18), object(9)
memory usage: 402.1+ KB
None

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102.0,Sales,1,2.0,Life Sciences,1,1,...,1.0,80,0,8,0,1.0,6,4,0,5
1,49,No,Travel_Frequently,279.0,Research & Development,8,1.0,Life Sciences,1,2,...,4.0,80,1,10,3,3.0,10,7,1,7
2,37,Yes,Travel_Rarely,1373.0,Research & Development,2,2.0,Other,1,4,...,2.0,80,0,7,3,3.0,0,0,0,0
3,33,No,Travel_Frequently,1392.0,Research & Development,3,4.0,Life Sciences,1,5,...,3.0,80,0,8,3,3.0,8,7,3,0
4,27,No,Travel_Rarely,591.0,Research & Development,2,1.0,Medical,1,7,...,4.0,80,1,6,3,3.0,2,2,2,2